accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns =[
    path('signup/',views.signup_view,name="signup"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
]

articles/urls.py
from django.urls import path
from . import views

app_name="articles"

urlpatterns=[
    path('',views.article_list,name='list'),
    path('create/',views.article_create,name='create'),
    path('<slug>',views.article_detail,name='detail'),
]

hello/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from . import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
    path('accounts/',include('accounts.urls')),
    path('',article_views.article_list,name="home"),
    path('about/',views.about),
    
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png',blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.DO_NOTHING)


    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:50]+'...'

articles/forms.py
from django.forms import ModelForm
from articles.models import Article

class CreateArticle(ModelForm):
    class Meta:
        model = Article
        fields = ['title','slug','body','thumb']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.

def signup_view(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))    
            return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    articles = Article.objects.order_by('-date')
    return render(request,'articles/article_list.html',{'articles' : articles})

def article_detail(request,slug):
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})

@login_required(login_url='/accounts/login/')
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form})

hello/views.py
from django.shortcuts import render


def home(request):
    return render(request,'home.html')

def about(request):
    return render(request,'about.html')

accounts/templates/accounts/login.html
{% extends 'main.html' %}

{% block content %}
    <div class="site-form">
        <h3>login</h3>
        <form action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}" >
            {% endif %}
            <input type="submit" id="pk" value="login">
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'main.html' %}

{% block content %}
    <div class="site-form">
        <h3>signup</h3>
        <form action="/accounts/signup/" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" id="pk" value="Signup">
        </form>
    </div>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'main.html' %}

{% block content %}
    <div class="site-form">
        <div class="yy">
            <h3>create article</h3>
            <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" id="pk" value="create">
            </form>
        </div>
    </div>
{% endblock%}

articles/templates/articles/article_detail.html
{% extends 'main.html' %}

{% block content %}
    <div class="article-detail">
        <div class="article">
            <img src="{{ article.thumb.url }}" style="height: 40vh;">
            
            <h1>{{ article.title }}</h1>
            <p>{{ article.date }}</p>
            <p>{{article.body}}</p>
        </div>
    </div>
{% endblock%}

articles/templates/articles/article_list.html
{% extends 'main.html' %}

{% block content %}
    <div class="articlepk">
        {% for article in articles %}
            <div class="article">
                
                <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
                <p>{{ article.date }}</p>
                <p>{{ article.snippet }}</p>
                <p class="author">added by {{ article.author.username }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>about</title>
</head>
<body>
    <h1>about</h1>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
</head>
<body>
    <h1>home</h1>
</body>
</html>

templates/main.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />
    <title>articlelist</title>
</head>
<body>
    <div class="project">
        <div class="main">
                <h1><a href="{%  url 'home' %}"><i class="fas fa-home">Home</i></a></h1>

            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'articles:create' %}">create</a></li>
                        <li>
                            <form action="{% url 'accounts:logout' %}" method="POST">
                                {% csrf_token %}
                                <button type="submit"> Logout</button>
                            </form>
                        </li>
                        
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
            <div class="wrapper">
                <h1>Article</h1>
                {% block content %}
                {% endblock %}
            </div>
    </div>
</body>
</html>